//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\GitHub\Sandpit\Compiler\SandpitAntlr\Sandpit.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class SandpitLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, ID=6, INT=7, NEWLINE=8, WS=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "ID", "LETTER", "INT", "NEWLINE", 
		"WS"
	};


	public SandpitLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SandpitLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'main'", "'end main'", "'constant'", "'='", "'var'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, "ID", "INT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sandpit.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SandpitLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\v', 'Q', '\b', '\x1', '\x4', '\x2', '\t', '\x2', '\x4', 
		'\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', 
		'\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', 
		'\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', 
		'\v', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', 
		'\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\a', '\a', '\x38', '\n', '\a', '\f', '\a', '\xE', 
		'\a', ';', '\v', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x6', '\t', 
		'@', '\n', '\t', '\r', '\t', '\xE', '\t', '\x41', '\x3', '\n', '\x5', 
		'\n', '\x45', '\n', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', 'I', 
		'\n', '\n', '\x3', '\v', '\x6', '\v', 'L', '\n', '\v', '\r', '\v', '\xE', 
		'\v', 'M', '\x3', '\v', '\x3', '\v', '\x2', '\x2', '\f', '\x3', '\x3', 
		'\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', 
		'\x2', '\x11', '\t', '\x13', '\n', '\x15', '\v', '\x3', '\x2', '\x5', 
		'\x3', '\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x4', 
		'\x2', '\v', '\v', '\"', '\"', '\x2', 'U', '\x2', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x3', '\x17', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '\x1C', '\x3', '\x2', '\x2', '\x2', '\a', 
		'%', '\x3', '\x2', '\x2', '\x2', '\t', '.', '\x3', '\x2', '\x2', '\x2', 
		'\v', '\x30', '\x3', '\x2', '\x2', '\x2', '\r', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '<', '\x3', '\x2', '\x2', '\x2', '\x11', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'H', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'K', '\x3', '\x2', '\x2', '\x2', '\x17', '\x18', '\a', 'o', '\x2', '\x2', 
		'\x18', '\x19', '\a', '\x63', '\x2', '\x2', '\x19', '\x1A', '\a', 'k', 
		'\x2', '\x2', '\x1A', '\x1B', '\a', 'p', '\x2', '\x2', '\x1B', '\x4', 
		'\x3', '\x2', '\x2', '\x2', '\x1C', '\x1D', '\a', 'g', '\x2', '\x2', '\x1D', 
		'\x1E', '\a', 'p', '\x2', '\x2', '\x1E', '\x1F', '\a', '\x66', '\x2', 
		'\x2', '\x1F', ' ', '\a', '\"', '\x2', '\x2', ' ', '!', '\a', 'o', '\x2', 
		'\x2', '!', '\"', '\a', '\x63', '\x2', '\x2', '\"', '#', '\a', 'k', '\x2', 
		'\x2', '#', '$', '\a', 'p', '\x2', '\x2', '$', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '%', '&', '\a', '\x65', '\x2', '\x2', '&', '\'', '\a', 'q', '\x2', 
		'\x2', '\'', '(', '\a', 'p', '\x2', '\x2', '(', ')', '\a', 'u', '\x2', 
		'\x2', ')', '*', '\a', 'v', '\x2', '\x2', '*', '+', '\a', '\x63', '\x2', 
		'\x2', '+', ',', '\a', 'p', '\x2', '\x2', ',', '-', '\a', 'v', '\x2', 
		'\x2', '-', '\b', '\x3', '\x2', '\x2', '\x2', '.', '/', '\a', '?', '\x2', 
		'\x2', '/', '\n', '\x3', '\x2', '\x2', '\x2', '\x30', '\x31', '\a', 'x', 
		'\x2', '\x2', '\x31', '\x32', '\a', '\x63', '\x2', '\x2', '\x32', '\x33', 
		'\a', 't', '\x2', '\x2', '\x33', '\f', '\x3', '\x2', '\x2', '\x2', '\x34', 
		'\x39', '\x5', '\xF', '\b', '\x2', '\x35', '\x38', '\x5', '\xF', '\b', 
		'\x2', '\x36', '\x38', '\t', '\x2', '\x2', '\x2', '\x37', '\x35', '\x3', 
		'\x2', '\x2', '\x2', '\x37', '\x36', '\x3', '\x2', '\x2', '\x2', '\x38', 
		';', '\x3', '\x2', '\x2', '\x2', '\x39', '\x37', '\x3', '\x2', '\x2', 
		'\x2', '\x39', ':', '\x3', '\x2', '\x2', '\x2', ':', '\xE', '\x3', '\x2', 
		'\x2', '\x2', ';', '\x39', '\x3', '\x2', '\x2', '\x2', '<', '=', '\t', 
		'\x3', '\x2', '\x2', '=', '\x10', '\x3', '\x2', '\x2', '\x2', '>', '@', 
		'\t', '\x2', '\x2', '\x2', '?', '>', '\x3', '\x2', '\x2', '\x2', '@', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x41', '?', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x42', '\x3', '\x2', '\x2', '\x2', '\x42', '\x12', '\x3', 
		'\x2', '\x2', '\x2', '\x43', '\x45', '\a', '\xF', '\x2', '\x2', '\x44', 
		'\x43', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', '\x2', '\x2', 
		'\x2', '\x45', '\x46', '\x3', '\x2', '\x2', '\x2', '\x46', 'I', '\a', 
		'\f', '\x2', '\x2', 'G', 'I', '\a', '\xF', '\x2', '\x2', 'H', '\x44', 
		'\x3', '\x2', '\x2', '\x2', 'H', 'G', '\x3', '\x2', '\x2', '\x2', 'I', 
		'\x14', '\x3', '\x2', '\x2', '\x2', 'J', 'L', '\t', '\x4', '\x2', '\x2', 
		'K', 'J', '\x3', '\x2', '\x2', '\x2', 'L', 'M', '\x3', '\x2', '\x2', '\x2', 
		'M', 'K', '\x3', '\x2', '\x2', '\x2', 'M', 'N', '\x3', '\x2', '\x2', '\x2', 
		'N', 'O', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\b', '\v', '\x2', '\x2', 
		'P', '\x16', '\x3', '\x2', '\x2', '\x2', '\t', '\x2', '\x37', '\x39', 
		'\x41', '\x44', 'H', 'M', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
