//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\GitHub\Sandpit\Compiler\SandpitAntlr\Sandpit.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class SandpitLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, ID=13, INT=14, NEWLINE=15, WS=16;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "ID", "LETTER", "INT", "NEWLINE", "WS"
	};


	public SandpitLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SandpitLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'main'", "'end main'", "'procedure'", "'('", "')'", "'end procedure'", 
		"'function'", "'end function'", "'constant'", "'='", "'var'", "'let'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "ID", "INT", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sandpit.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SandpitLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x12', '\x95', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', 
		'|', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x7F', '\v', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x6', '\x10', '\x84', '\n', '\x10', 
		'\r', '\x10', '\xE', '\x10', '\x85', '\x3', '\x11', '\x5', '\x11', '\x89', 
		'\n', '\x11', '\x3', '\x11', '\x3', '\x11', '\x5', '\x11', '\x8D', '\n', 
		'\x11', '\x3', '\x12', '\x6', '\x12', '\x90', '\n', '\x12', '\r', '\x12', 
		'\xE', '\x12', '\x91', '\x3', '\x12', '\x3', '\x12', '\x2', '\x2', '\x13', 
		'\x3', '\x3', '\x5', '\x4', '\a', '\x5', '\t', '\x6', '\v', '\a', '\r', 
		'\b', '\xF', '\t', '\x11', '\n', '\x13', '\v', '\x15', '\f', '\x17', '\r', 
		'\x19', '\xE', '\x1B', '\xF', '\x1D', '\x2', '\x1F', '\x10', '!', '\x11', 
		'#', '\x12', '\x3', '\x2', '\x5', '\x3', '\x2', '\x32', ';', '\x4', '\x2', 
		'\x43', '\\', '\x63', '|', '\x4', '\x2', '\v', '\v', '\"', '\"', '\x2', 
		'\x99', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x3', '%', '\x3', '\x2', '\x2', '\x2', '\x5', '*', 
		'\x3', '\x2', '\x2', '\x2', '\a', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\t', '=', '\x3', '\x2', '\x2', '\x2', '\v', '?', '\x3', '\x2', '\x2', 
		'\x2', '\r', '\x41', '\x3', '\x2', '\x2', '\x2', '\xF', 'O', '\x3', '\x2', 
		'\x2', '\x2', '\x11', 'X', '\x3', '\x2', '\x2', '\x2', '\x13', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x15', 'n', '\x3', '\x2', '\x2', '\x2', '\x17', 
		'p', '\x3', '\x2', '\x2', '\x2', '\x19', 't', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', 'x', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x80', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\x83', '\x3', '\x2', '\x2', '\x2', '!', '\x8C', 
		'\x3', '\x2', '\x2', '\x2', '#', '\x8F', '\x3', '\x2', '\x2', '\x2', '%', 
		'&', '\a', 'o', '\x2', '\x2', '&', '\'', '\a', '\x63', '\x2', '\x2', '\'', 
		'(', '\a', 'k', '\x2', '\x2', '(', ')', '\a', 'p', '\x2', '\x2', ')', 
		'\x4', '\x3', '\x2', '\x2', '\x2', '*', '+', '\a', 'g', '\x2', '\x2', 
		'+', ',', '\a', 'p', '\x2', '\x2', ',', '-', '\a', '\x66', '\x2', '\x2', 
		'-', '.', '\a', '\"', '\x2', '\x2', '.', '/', '\a', 'o', '\x2', '\x2', 
		'/', '\x30', '\a', '\x63', '\x2', '\x2', '\x30', '\x31', '\a', 'k', '\x2', 
		'\x2', '\x31', '\x32', '\a', 'p', '\x2', '\x2', '\x32', '\x6', '\x3', 
		'\x2', '\x2', '\x2', '\x33', '\x34', '\a', 'r', '\x2', '\x2', '\x34', 
		'\x35', '\a', 't', '\x2', '\x2', '\x35', '\x36', '\a', 'q', '\x2', '\x2', 
		'\x36', '\x37', '\a', '\x65', '\x2', '\x2', '\x37', '\x38', '\a', 'g', 
		'\x2', '\x2', '\x38', '\x39', '\a', '\x66', '\x2', '\x2', '\x39', ':', 
		'\a', 'w', '\x2', '\x2', ':', ';', '\a', 't', '\x2', '\x2', ';', '<', 
		'\a', 'g', '\x2', '\x2', '<', '\b', '\x3', '\x2', '\x2', '\x2', '=', '>', 
		'\a', '*', '\x2', '\x2', '>', '\n', '\x3', '\x2', '\x2', '\x2', '?', '@', 
		'\a', '+', '\x2', '\x2', '@', '\f', '\x3', '\x2', '\x2', '\x2', '\x41', 
		'\x42', '\a', 'g', '\x2', '\x2', '\x42', '\x43', '\a', 'p', '\x2', '\x2', 
		'\x43', '\x44', '\a', '\x66', '\x2', '\x2', '\x44', '\x45', '\a', '\"', 
		'\x2', '\x2', '\x45', '\x46', '\a', 'r', '\x2', '\x2', '\x46', 'G', '\a', 
		't', '\x2', '\x2', 'G', 'H', '\a', 'q', '\x2', '\x2', 'H', 'I', '\a', 
		'\x65', '\x2', '\x2', 'I', 'J', '\a', 'g', '\x2', '\x2', 'J', 'K', '\a', 
		'\x66', '\x2', '\x2', 'K', 'L', '\a', 'w', '\x2', '\x2', 'L', 'M', '\a', 
		't', '\x2', '\x2', 'M', 'N', '\a', 'g', '\x2', '\x2', 'N', '\xE', '\x3', 
		'\x2', '\x2', '\x2', 'O', 'P', '\a', 'h', '\x2', '\x2', 'P', 'Q', '\a', 
		'w', '\x2', '\x2', 'Q', 'R', '\a', 'p', '\x2', '\x2', 'R', 'S', '\a', 
		'\x65', '\x2', '\x2', 'S', 'T', '\a', 'v', '\x2', '\x2', 'T', 'U', '\a', 
		'k', '\x2', '\x2', 'U', 'V', '\a', 'q', '\x2', '\x2', 'V', 'W', '\a', 
		'p', '\x2', '\x2', 'W', '\x10', '\x3', '\x2', '\x2', '\x2', 'X', 'Y', 
		'\a', 'g', '\x2', '\x2', 'Y', 'Z', '\a', 'p', '\x2', '\x2', 'Z', '[', 
		'\a', '\x66', '\x2', '\x2', '[', '\\', '\a', '\"', '\x2', '\x2', '\\', 
		']', '\a', 'h', '\x2', '\x2', ']', '^', '\a', 'w', '\x2', '\x2', '^', 
		'_', '\a', 'p', '\x2', '\x2', '_', '`', '\a', '\x65', '\x2', '\x2', '`', 
		'\x61', '\a', 'v', '\x2', '\x2', '\x61', '\x62', '\a', 'k', '\x2', '\x2', 
		'\x62', '\x63', '\a', 'q', '\x2', '\x2', '\x63', '\x64', '\a', 'p', '\x2', 
		'\x2', '\x64', '\x12', '\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', 
		'\x65', '\x2', '\x2', '\x66', 'g', '\a', 'q', '\x2', '\x2', 'g', 'h', 
		'\a', 'p', '\x2', '\x2', 'h', 'i', '\a', 'u', '\x2', '\x2', 'i', 'j', 
		'\a', 'v', '\x2', '\x2', 'j', 'k', '\a', '\x63', '\x2', '\x2', 'k', 'l', 
		'\a', 'p', '\x2', '\x2', 'l', 'm', '\a', 'v', '\x2', '\x2', 'm', '\x14', 
		'\x3', '\x2', '\x2', '\x2', 'n', 'o', '\a', '?', '\x2', '\x2', 'o', '\x16', 
		'\x3', '\x2', '\x2', '\x2', 'p', 'q', '\a', 'x', '\x2', '\x2', 'q', 'r', 
		'\a', '\x63', '\x2', '\x2', 'r', 's', '\a', 't', '\x2', '\x2', 's', '\x18', 
		'\x3', '\x2', '\x2', '\x2', 't', 'u', '\a', 'n', '\x2', '\x2', 'u', 'v', 
		'\a', 'g', '\x2', '\x2', 'v', 'w', '\a', 'v', '\x2', '\x2', 'w', '\x1A', 
		'\x3', '\x2', '\x2', '\x2', 'x', '}', '\x5', '\x1D', '\xF', '\x2', 'y', 
		'|', '\x5', '\x1D', '\xF', '\x2', 'z', '|', '\t', '\x2', '\x2', '\x2', 
		'{', 'y', '\x3', '\x2', '\x2', '\x2', '{', 'z', '\x3', '\x2', '\x2', '\x2', 
		'|', '\x7F', '\x3', '\x2', '\x2', '\x2', '}', '{', '\x3', '\x2', '\x2', 
		'\x2', '}', '~', '\x3', '\x2', '\x2', '\x2', '~', '\x1C', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x80', '\x81', 
		'\t', '\x3', '\x2', '\x2', '\x81', '\x1E', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x84', '\t', '\x2', '\x2', '\x2', '\x83', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x84', '\x85', '\x3', '\x2', '\x2', '\x2', '\x85', '\x83', 
		'\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\x3', '\x2', '\x2', '\x2', 
		'\x86', ' ', '\x3', '\x2', '\x2', '\x2', '\x87', '\x89', '\a', '\xF', 
		'\x2', '\x2', '\x88', '\x87', '\x3', '\x2', '\x2', '\x2', '\x88', '\x89', 
		'\x3', '\x2', '\x2', '\x2', '\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', 
		'\x8A', '\x8D', '\a', '\f', '\x2', '\x2', '\x8B', '\x8D', '\a', '\xF', 
		'\x2', '\x2', '\x8C', '\x88', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '\x8D', '\"', '\x3', '\x2', '\x2', '\x2', 
		'\x8E', '\x90', '\t', '\x4', '\x2', '\x2', '\x8F', '\x8E', '\x3', '\x2', 
		'\x2', '\x2', '\x90', '\x91', '\x3', '\x2', '\x2', '\x2', '\x91', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x91', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x92', '\x93', '\x3', '\x2', '\x2', '\x2', '\x93', '\x94', '\b', '\x12', 
		'\x2', '\x2', '\x94', '$', '\x3', '\x2', '\x2', '\x2', '\t', '\x2', '{', 
		'}', '\x85', '\x88', '\x8C', '\x91', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
