//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\GitHub\Sandpit\Compiler\SandpitAntlr\Sandpit.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class SandpitLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, ID=22, INT=23, STRING=24, NEWLINE=25, 
		WS=26;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "T__7", "T__8", 
		"T__9", "T__10", "T__11", "T__12", "T__13", "T__14", "T__15", "T__16", 
		"T__17", "T__18", "T__19", "T__20", "ID", "LETTER", "INT", "STRING", "NEWLINE", 
		"WS"
	};


	public SandpitLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SandpitLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'main'", "'end main'", "'procedure'", "'('", "')'", "'end procedure'", 
		"'function'", "':'", "'end function'", "'constant'", "'='", "'var'", "'let'", 
		"'while'", "'end while'", "'{'", "','", "'}'", "'Integer'", "'String'", 
		"'return'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, "ID", "INT", 
		"STRING", "NEWLINE", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Sandpit.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SandpitLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x1C', '\xE0', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\f', 
		'\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\a', '\x17', '\xBE', '\n', '\x17', '\f', '\x17', '\xE', '\x17', 
		'\xC1', '\v', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x6', 
		'\x19', '\xC6', '\n', '\x19', '\r', '\x19', '\xE', '\x19', '\xC7', '\x3', 
		'\x1A', '\x3', '\x1A', '\a', '\x1A', '\xCC', '\n', '\x1A', '\f', '\x1A', 
		'\xE', '\x1A', '\xCF', '\v', '\x1A', '\x3', '\x1A', '\x3', '\x1A', '\x3', 
		'\x1B', '\x5', '\x1B', '\xD4', '\n', '\x1B', '\x3', '\x1B', '\x3', '\x1B', 
		'\x5', '\x1B', '\xD8', '\n', '\x1B', '\x3', '\x1C', '\x6', '\x1C', '\xDB', 
		'\n', '\x1C', '\r', '\x1C', '\xE', '\x1C', '\xDC', '\x3', '\x1C', '\x3', 
		'\x1C', '\x2', '\x2', '\x1D', '\x3', '\x3', '\x5', '\x4', '\a', '\x5', 
		'\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', '\x13', 
		'\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', '\x1D', 
		'\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', '\'', '\x15', 
		')', '\x16', '+', '\x17', '-', '\x18', '/', '\x2', '\x31', '\x19', '\x33', 
		'\x1A', '\x35', '\x1B', '\x37', '\x1C', '\x3', '\x2', '\x6', '\x3', '\x2', 
		'\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x6', '\x2', '\"', 
		'\"', '\x32', ';', '\x43', '\\', '\x63', '|', '\x4', '\x2', '\v', '\v', 
		'\"', '\"', '\x2', '\xE5', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\t', '\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', 
		'\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '\x39', '\x3', '\x2', '\x2', '\x2', '\x5', '>', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'G', '\x3', '\x2', '\x2', '\x2', '\t', 'Q', 
		'\x3', '\x2', '\x2', '\x2', '\v', 'S', '\x3', '\x2', '\x2', '\x2', '\r', 
		'U', '\x3', '\x2', '\x2', '\x2', '\xF', '\x63', '\x3', '\x2', '\x2', '\x2', 
		'\x11', 'l', '\x3', '\x2', '\x2', '\x2', '\x13', 'n', '\x3', '\x2', '\x2', 
		'\x2', '\x15', '{', '\x3', '\x2', '\x2', '\x2', '\x17', '\x84', '\x3', 
		'\x2', '\x2', '\x2', '\x19', '\x86', '\x3', '\x2', '\x2', '\x2', '\x1B', 
		'\x8A', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x8E', '\x3', '\x2', '\x2', 
		'\x2', '\x1F', '\x94', '\x3', '\x2', '\x2', '\x2', '!', '\x9E', '\x3', 
		'\x2', '\x2', '\x2', '#', '\xA0', '\x3', '\x2', '\x2', '\x2', '%', '\xA2', 
		'\x3', '\x2', '\x2', '\x2', '\'', '\xA4', '\x3', '\x2', '\x2', '\x2', 
		')', '\xAC', '\x3', '\x2', '\x2', '\x2', '+', '\xB3', '\x3', '\x2', '\x2', 
		'\x2', '-', '\xBA', '\x3', '\x2', '\x2', '\x2', '/', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\xC5', '\x3', '\x2', '\x2', '\x2', '\x33', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', '\x35', '\xD7', '\x3', '\x2', '\x2', '\x2', 
		'\x37', '\xDA', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\a', 'o', '\x2', 
		'\x2', ':', ';', '\a', '\x63', '\x2', '\x2', ';', '<', '\a', 'k', '\x2', 
		'\x2', '<', '=', '\a', 'p', '\x2', '\x2', '=', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '>', '?', '\a', 'g', '\x2', '\x2', '?', '@', '\a', 'p', '\x2', 
		'\x2', '@', '\x41', '\a', '\x66', '\x2', '\x2', '\x41', '\x42', '\a', 
		'\"', '\x2', '\x2', '\x42', '\x43', '\a', 'o', '\x2', '\x2', '\x43', '\x44', 
		'\a', '\x63', '\x2', '\x2', '\x44', '\x45', '\a', 'k', '\x2', '\x2', '\x45', 
		'\x46', '\a', 'p', '\x2', '\x2', '\x46', '\x6', '\x3', '\x2', '\x2', '\x2', 
		'G', 'H', '\a', 'r', '\x2', '\x2', 'H', 'I', '\a', 't', '\x2', '\x2', 
		'I', 'J', '\a', 'q', '\x2', '\x2', 'J', 'K', '\a', '\x65', '\x2', '\x2', 
		'K', 'L', '\a', 'g', '\x2', '\x2', 'L', 'M', '\a', '\x66', '\x2', '\x2', 
		'M', 'N', '\a', 'w', '\x2', '\x2', 'N', 'O', '\a', 't', '\x2', '\x2', 
		'O', 'P', '\a', 'g', '\x2', '\x2', 'P', '\b', '\x3', '\x2', '\x2', '\x2', 
		'Q', 'R', '\a', '*', '\x2', '\x2', 'R', '\n', '\x3', '\x2', '\x2', '\x2', 
		'S', 'T', '\a', '+', '\x2', '\x2', 'T', '\f', '\x3', '\x2', '\x2', '\x2', 
		'U', 'V', '\a', 'g', '\x2', '\x2', 'V', 'W', '\a', 'p', '\x2', '\x2', 
		'W', 'X', '\a', '\x66', '\x2', '\x2', 'X', 'Y', '\a', '\"', '\x2', '\x2', 
		'Y', 'Z', '\a', 'r', '\x2', '\x2', 'Z', '[', '\a', 't', '\x2', '\x2', 
		'[', '\\', '\a', 'q', '\x2', '\x2', '\\', ']', '\a', '\x65', '\x2', '\x2', 
		']', '^', '\a', 'g', '\x2', '\x2', '^', '_', '\a', '\x66', '\x2', '\x2', 
		'_', '`', '\a', 'w', '\x2', '\x2', '`', '\x61', '\a', 't', '\x2', '\x2', 
		'\x61', '\x62', '\a', 'g', '\x2', '\x2', '\x62', '\xE', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\a', 'h', '\x2', '\x2', '\x64', '\x65', 
		'\a', 'w', '\x2', '\x2', '\x65', '\x66', '\a', 'p', '\x2', '\x2', '\x66', 
		'g', '\a', '\x65', '\x2', '\x2', 'g', 'h', '\a', 'v', '\x2', '\x2', 'h', 
		'i', '\a', 'k', '\x2', '\x2', 'i', 'j', '\a', 'q', '\x2', '\x2', 'j', 
		'k', '\a', 'p', '\x2', '\x2', 'k', '\x10', '\x3', '\x2', '\x2', '\x2', 
		'l', 'm', '\a', '<', '\x2', '\x2', 'm', '\x12', '\x3', '\x2', '\x2', '\x2', 
		'n', 'o', '\a', 'g', '\x2', '\x2', 'o', 'p', '\a', 'p', '\x2', '\x2', 
		'p', 'q', '\a', '\x66', '\x2', '\x2', 'q', 'r', '\a', '\"', '\x2', '\x2', 
		'r', 's', '\a', 'h', '\x2', '\x2', 's', 't', '\a', 'w', '\x2', '\x2', 
		't', 'u', '\a', 'p', '\x2', '\x2', 'u', 'v', '\a', '\x65', '\x2', '\x2', 
		'v', 'w', '\a', 'v', '\x2', '\x2', 'w', 'x', '\a', 'k', '\x2', '\x2', 
		'x', 'y', '\a', 'q', '\x2', '\x2', 'y', 'z', '\a', 'p', '\x2', '\x2', 
		'z', '\x14', '\x3', '\x2', '\x2', '\x2', '{', '|', '\a', '\x65', '\x2', 
		'\x2', '|', '}', '\a', 'q', '\x2', '\x2', '}', '~', '\a', 'p', '\x2', 
		'\x2', '~', '\x7F', '\a', 'u', '\x2', '\x2', '\x7F', '\x80', '\a', 'v', 
		'\x2', '\x2', '\x80', '\x81', '\a', '\x63', '\x2', '\x2', '\x81', '\x82', 
		'\a', 'p', '\x2', '\x2', '\x82', '\x83', '\a', 'v', '\x2', '\x2', '\x83', 
		'\x16', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', '\a', '?', '\x2', 
		'\x2', '\x85', '\x18', '\x3', '\x2', '\x2', '\x2', '\x86', '\x87', '\a', 
		'x', '\x2', '\x2', '\x87', '\x88', '\a', '\x63', '\x2', '\x2', '\x88', 
		'\x89', '\a', 't', '\x2', '\x2', '\x89', '\x1A', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '\x8B', '\a', 'n', '\x2', '\x2', '\x8B', '\x8C', '\a', 
		'g', '\x2', '\x2', '\x8C', '\x8D', '\a', 'v', '\x2', '\x2', '\x8D', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', 'y', '\x2', '\x2', '\x8F', 
		'\x90', '\a', 'j', '\x2', '\x2', '\x90', '\x91', '\a', 'k', '\x2', '\x2', 
		'\x91', '\x92', '\a', 'n', '\x2', '\x2', '\x92', '\x93', '\a', 'g', '\x2', 
		'\x2', '\x93', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x94', '\x95', '\a', 
		'g', '\x2', '\x2', '\x95', '\x96', '\a', 'p', '\x2', '\x2', '\x96', '\x97', 
		'\a', '\x66', '\x2', '\x2', '\x97', '\x98', '\a', '\"', '\x2', '\x2', 
		'\x98', '\x99', '\a', 'y', '\x2', '\x2', '\x99', '\x9A', '\a', 'j', '\x2', 
		'\x2', '\x9A', '\x9B', '\a', 'k', '\x2', '\x2', '\x9B', '\x9C', '\a', 
		'n', '\x2', '\x2', '\x9C', '\x9D', '\a', 'g', '\x2', '\x2', '\x9D', ' ', 
		'\x3', '\x2', '\x2', '\x2', '\x9E', '\x9F', '\a', '}', '\x2', '\x2', '\x9F', 
		'\"', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '.', '\x2', '\x2', 
		'\xA1', '$', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA3', '\a', '\x7F', 
		'\x2', '\x2', '\xA3', '&', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', 
		'\a', 'K', '\x2', '\x2', '\xA5', '\xA6', '\a', 'p', '\x2', '\x2', '\xA6', 
		'\xA7', '\a', 'v', '\x2', '\x2', '\xA7', '\xA8', '\a', 'g', '\x2', '\x2', 
		'\xA8', '\xA9', '\a', 'i', '\x2', '\x2', '\xA9', '\xAA', '\a', 'g', '\x2', 
		'\x2', '\xAA', '\xAB', '\a', 't', '\x2', '\x2', '\xAB', '(', '\x3', '\x2', 
		'\x2', '\x2', '\xAC', '\xAD', '\a', 'U', '\x2', '\x2', '\xAD', '\xAE', 
		'\a', 'v', '\x2', '\x2', '\xAE', '\xAF', '\a', 't', '\x2', '\x2', '\xAF', 
		'\xB0', '\a', 'k', '\x2', '\x2', '\xB0', '\xB1', '\a', 'p', '\x2', '\x2', 
		'\xB1', '\xB2', '\a', 'i', '\x2', '\x2', '\xB2', '*', '\x3', '\x2', '\x2', 
		'\x2', '\xB3', '\xB4', '\a', 't', '\x2', '\x2', '\xB4', '\xB5', '\a', 
		'g', '\x2', '\x2', '\xB5', '\xB6', '\a', 'v', '\x2', '\x2', '\xB6', '\xB7', 
		'\a', 'w', '\x2', '\x2', '\xB7', '\xB8', '\a', 't', '\x2', '\x2', '\xB8', 
		'\xB9', '\a', 'p', '\x2', '\x2', '\xB9', ',', '\x3', '\x2', '\x2', '\x2', 
		'\xBA', '\xBF', '\x5', '/', '\x18', '\x2', '\xBB', '\xBE', '\x5', '/', 
		'\x18', '\x2', '\xBC', '\xBE', '\t', '\x2', '\x2', '\x2', '\xBD', '\xBB', 
		'\x3', '\x2', '\x2', '\x2', '\xBD', '\xBC', '\x3', '\x2', '\x2', '\x2', 
		'\xBE', '\xC1', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xBD', '\x3', '\x2', 
		'\x2', '\x2', '\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '.', 
		'\x3', '\x2', '\x2', '\x2', '\xC1', '\xBF', '\x3', '\x2', '\x2', '\x2', 
		'\xC2', '\xC3', '\t', '\x3', '\x2', '\x2', '\xC3', '\x30', '\x3', '\x2', 
		'\x2', '\x2', '\xC4', '\xC6', '\t', '\x2', '\x2', '\x2', '\xC5', '\xC4', 
		'\x3', '\x2', '\x2', '\x2', '\xC6', '\xC7', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC7', '\xC8', '\x3', '\x2', 
		'\x2', '\x2', '\xC8', '\x32', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xCD', 
		'\a', '$', '\x2', '\x2', '\xCA', '\xCC', '\t', '\x4', '\x2', '\x2', '\xCB', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xCF', '\x3', '\x2', '\x2', 
		'\x2', '\xCD', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xCD', '\xCE', '\x3', 
		'\x2', '\x2', '\x2', '\xCE', '\xD0', '\x3', '\x2', '\x2', '\x2', '\xCF', 
		'\xCD', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\a', '$', '\x2', 
		'\x2', '\xD1', '\x34', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD4', '\a', 
		'\xF', '\x2', '\x2', '\xD3', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD3', 
		'\xD4', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD5', '\x3', '\x2', '\x2', 
		'\x2', '\xD5', '\xD8', '\a', '\f', '\x2', '\x2', '\xD6', '\xD8', '\a', 
		'\xF', '\x2', '\x2', '\xD7', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD7', 
		'\xD6', '\x3', '\x2', '\x2', '\x2', '\xD8', '\x36', '\x3', '\x2', '\x2', 
		'\x2', '\xD9', '\xDB', '\t', '\x5', '\x2', '\x2', '\xDA', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'\xDA', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', '\x3', '\x2', '\x2', 
		'\x2', '\xDD', '\xDE', '\x3', '\x2', '\x2', '\x2', '\xDE', '\xDF', '\b', 
		'\x1C', '\x2', '\x2', '\xDF', '\x38', '\x3', '\x2', '\x2', '\x2', '\n', 
		'\x2', '\xBD', '\xBF', '\xC7', '\xCD', '\xD3', '\xD7', '\xDC', '\x3', 
		'\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
